<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FighterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FighterRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                ''
            )
            ->getResult();
    }
}
